version: '3.9'

networks:
  t_store_network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    env_file: .env
    container_name: stylehub_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
    hostname: t_store_2024
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./t_storeDB:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - t_store_network

  app:
    build: 
      context: .
      dockerfile: backend/Dockerfile 
    container_name: app_api

    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      TZ: America/Sao_Paulo
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: exampledb
    
    networks:
      - t_store_network
